export {topDiarioCommand} from './topDiario';
export {TopAntipalaCommand} from './topAntipala';
export {pingCommand} from './ping';
export {repoCommand} from './repo';
export {sugerirCommand} from './sugerir';
export {sugerenciasCommand} from './sugerencias';
export {chisteCommand, guardarChisteCommand} from './chistes';
export {banCommand, unbanCommand} from './ban';
export {adminCommand, adminRemoveCommand} from './admin';
export {setToperoCommand} from './setTopero';
export {crearToperoCommand} from './crearTopero';
export {audioCommand} from './audio';
export {helpAudioCommand} from './helpAudio';
export {helpImagenCommand} from './helpImagen';
export {guardarAudioCommand} from './guardarAudio';
export {guardarImagenCommand} from './guardarImagen';
export {imagenCommand} from './imagen';
export {editarAudioCommand} from './editarAudio';
export {crearAudioCommand} from './crearAudio';
export {editarImagenCommand} from './editarImagen';
export {showAllTopsCommand} from './showAllTops';
export {showTopOfCommand} from './showTopOf';
export {uploadFinalCommand} from './uploadFinal';
export {uploadAbsencesCommand} from './uploadAbsences';
